//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifuWeatherWarnMap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GifuWeatherWarnMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;GeometryCollection&quot;, &quot;geometries&quot;: [
        ///{&quot;type&quot;:&quot;MultiPolygon&quot;,&quot;coordinates&quot;:[[[[141.19919221844623,45.25882138659779],[141.18924693879524,45.25683889230112],[141.18761389136807,45.25218194643975],[141.18319944230052,45.25306861322599],[141.17909944208566,45.24999666671283],[141.17606306106143,45.24306889221566],[141.17046333341614,45.238467224982514],[141.16377916997283,45.23846361330516],[141.15612194637083,45.23513361262616],[141.153206667154,45.23240805438826],[141.15005333289503,45.22479417091432 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaForecastLocalM_prefecture_GIS_0_5 {
            get {
                return ResourceManager.GetString("AreaForecastLocalM_prefecture_GIS_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;, &quot;features&quot;: [
        ///{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;MultiPolygon&quot;,&quot;coordinates&quot;:[[[[141.19919221844623,45.25882138659779],[141.17909944208566,45.24999666671283],[141.13237916986282,45.21345638730247],[141.14172610897276,45.1903997206706],[141.1292494419083,45.18439166664217],[141.14098111508645,45.16217833296378],[141.16569555060926,45.137464440631504],[141.2042997282499,45.113954441044655],[141.2484152787422,45.10323610776021],[141.28626596570177,45.11457846802193],[141.3294733 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaForecastLocalM_prefecture_GIS_20190125_01 {
            get {
                return ResourceManager.GetString("AreaForecastLocalM_prefecture_GIS_20190125_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;GeometryCollection&quot;, &quot;geometries&quot;: [
        ///{&quot;type&quot;:&quot;Polygon&quot;,&quot;coordinates&quot;:[[[140.21591204900187,39.863141946443704],[140.20044613528103,39.86394005429014],[140.19778116706732,39.859791172324776],[140.19904286553583,39.85558255918778],[140.1862942542765,39.84829563953218],[140.17518949400005,39.84475317132183],[140.16664642019623,39.84468513581044],[140.155254086407,39.84958102794212],[140.1471596367079,39.84468633280807],[140.13289763911484,39.84490194616791],[140.1175253052487,39.85070146809835],[140.1 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaInformationCity_weather_GIS_0_5 {
            get {
                return ResourceManager.GetString("AreaInformationCity_weather_GIS_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;type&quot;:&quot;FeatureCollection&quot;, &quot;features&quot;: [
        ///{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;Polygon&quot;,&quot;coordinates&quot;:[[[140.21591204900187,39.863141946443704],[140.20044613528103,39.86394005429014],[140.19778116706732,39.859791172324776],[140.19904286553583,39.85558255918778],[140.1862942542765,39.84829563953218],[140.17518949400005,39.84475317132183],[140.16664642019623,39.84468513581044],[140.155254086407,39.84958102794212],[140.1471596367079,39.84468633280807],[140.13289763911484,39.84490194616791],[140.1175253052487 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AreaInformationCity_weather_GIS_0_5_Name {
            get {
                return ResourceManager.GetString("AreaInformationCity_weather_GIS_0_5_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AreaForecastLocalM_prefecture_GIS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
